farben_amerikanisch:
  blitze: '#ffffff'
  helligkeit: '0.5'
  hoher_wind: '#ffff00'
  ifr: '#ff0000'
  ifr_bei_wind: '#7d0000'
  lifr: '#7d007d'
  lifr_bei_wind: '#4b004b'
  mvfr: '#0000ff'
  mvfr_bei_wind: '#00007d'
  vfr: '#00ff00'
  vfr_bei_wind: '#007d00'
farben_gafor:
  blitze: '#ffffff'
  charlie: '#00ADEF'
  charlie_bei_wind: '#005577'
  delta: '#FEF200'
  delta_bei_wind: '#7f7800'
  helligkeit: '0.5'
  mike: '#F7921C'
  mike_bei_wind: '#7b490e'
  oscar: '#4EB849'
  oscar_bei_wind: '#275c24'
  xray: '#ED1B24'
  xray_bei_wind: '#760d12'
flugplaetze:
  - "LOXZ"
  - "NULL"
  - "LOWL"
  - "LOWS"
  - "EDDM"
  - "EDMO"
  - "LOWI"
  - "ETHA"
  - "ETSL"
  - "ETSI"
  - "ETIH"
  - "ETIC"
  - "LKLN"
  - "LKPR"
  - "LKKV"
  - "EDQM"
  - "EDDE"
  - "EDBC"
  - "EDDP"
  - "EDAC"
  - "EDDC"
  - "ETSH"
  - "EDDB"
  - "NULL"
  - "EPSC"
  - "EDAH"
  - "NULL"
  - "ETNL"
  - "EDHL"
  - "EDHK"
  - "ETNH"
  - "EDXW"
  - "NULL"
  - "EDDH"
  - "EDHI"
  - "ETMN"
  - "ETNT"
  - "EDWE"
  - "EHGG"
  - "ETWM"
  - "EDDG"
  - "ETND"
  - "EDDW"
  - "ETHS"
  - "EDVE"
  - "ETHC"
  - "EDDV"
  - "ETNW"
  - "ETHB"
  - "EDVK"
  - "ETHF"
  - "EDLP"
  - "EDLW"
  - "EDDL"
  - "EDLV"
  - "EDLN"
  - "ETNG"
  - "ETNN"
  - "EDDK"
  - "EDGS"
  - "EDDF"
  - "ETOU"
  - "EDFH"
  - "ETSB"
  - "ETAD"
  - "ELLX"
  - "ETEK"
  - "EDDR"
  - "ETAR"
  - "EDFM"
  - "EDTY"
  - "ETHN"
  - "ETIK"
  - "ETEB"
  - "EDDN"
  - "ETSN"
  - "EDMA"
  - "EDJA"
  - "EDNY"
  - "ETHL"
  - "EDDS"
  - "EDSB"
  - "EDTL"
  - "LSZH"
  - "LFSB"
  - "LSZB"
version: gafor
wind:
  frequenz: '1'
  hoch: '25'
  normal: '15'
wlan:
  passwort: vqjaynua
  ssid: FRITZ!Box 7590 TN Kellervorraum
zeiten:
  an: '8'
  aus: '22'
