farben:
  blitze: '#ffffff'
  helligkeit: '0.5'
  hoher_wind: '#ffff00'
  ifr: '#ff0000'
  ifr_bei_wind: '#7d0000'
  lifr: '#7d007d'
  lifr_bei_wind: '#4b004b'
  mvfr: '#0000ff'
  mvfr_bei_wind: '#00007d'
  vfr: '#00ff00'
  vfr_bei_wind: '#007d00'
flugplaetze:
- EDDR
- ETAR
- ETEK
- ELLX
- ETAD
- ETSB
- EDFH
- ETOU
- EDDF
- EDFM
- EDSB
- EDTL
- LFSB
- LSZH
- EDNY
- ETHL
- EDJA
- ETSL
- ETHA
- LOWI
- 'NULL'
- LOWS
- 'NULL'
- EDMO
- EDDM
- EDMA
- ETSI
- ETSN
- 'NULL'
- EDDS
- EDTY
- ETHN
- ETIK
- ETEB
- EDDN
- ETIH
- ETIC
- EDQM
- LKKV
- LKLN
- 'NULL'
- EDAC
- EDDP
- EDBC
- 'NULL'
- EDDE
- 'NULL'
- ETHF
- EDVK
- EDLP
- EDGS
- EDDK
- ETNN
- ETNG
- EDLN
- EDDL
- EDLV
- 'NULL'
- EDLW
- EDDG
- ETWM
- EHGG
- EDWE
- ETNT
- ETMN
- 'NULL'
- EDXW
- ETNH
- 'NULL'
- EDHK
- EDHL
- EDDH
- EDHI
- ETHS
- EDVE
- ETHC
- EDDV
- ETNW
- ETHB
- ETND
- EDDW
- ETNL
- EDAH
- 'NULL'
- EPSC
- EDDB
- 'NULL'
- 'NULL'
- ETSH
- EDDC
wind:
  frequenz: '1'
  hoch: '25'
  normal: '15'
wlan:
  passwort: 0123456789
  ssid: FRITZ!Box 7590 TN
zeiten:
  an: '8'
  aus: '22'
