farben_amerikanisch:
  blitze-amerikanisch: '#ffffff'
  hoher_wind: '#ffff00'
  ifr: '#ff0000'
  ifr_bei_wind: '#7d0000'
  lifr: '#7d007d'
  lifr_bei_wind: '#4b004b'
  mvfr: '#0000ff'
  mvfr_bei_wind: '#00007d'
  vfr: '#00ff00'
  vfr_bei_wind: '#007d00'
farben_gafor:
  blitze-gafor: '#ffffff'
  charlie: '#0038ff'
  charlie_bei_wind: '#001c80'
  delta: '#ffff00'
  delta_bei_wind: '#808000'
  mike: '#ff8800'
  mike_bei_wind: '#804400'
  oscar: '#32ae00'
  oscar_bei_wind: '#195700'
  xray: '#c90000'
  xray_bei_wind: '#640000'
flugplaetze:
- LOXZ
- 'NULL'
- LOWL
- LOWS
- EDDM
- EDMO
- LOWI
- ETHA
- ETSL
- ETSI
- ETIH
- ETIC
- LKLN
- LKPR
- LKKV
- EDQM
- EDDE
- EDBC
- EDDP
- EDAC
- EDDC
- ETSH
- EDDB
- 'NULL'
- EPSC
- EDAH
- 'NULL'
- ETNL
- EDHL
- EDHK
- ETNH
- 'NULL'
- EDXW
- 'NULL'
- EDDH
- EDHI
- ETMN
- ETNT
- EDWE
- EHGG
- ETWM
- EDDG
- ETND
- EDDW
- ETHS
- EDVE
- ETHC
- EDDV
- ETNW
- ETHB
- EDVK
- ETHF
- EDLP
- EDLW
- EDDL
- EDLV
- EDLN
- ETNG
- ETNN
- EDDK
- EDGS
- EDDF
- ETOU
- EDFH
- ETSB
- ETAD
- ELLX
- ETEK
- EDDR
- ETAR
- EDFM
- EDTY
- ETHN
- ETIK
- ETEB
- EDDN
- ETSN
- EDMA
- EDJA
- EDNY
- ETHL
- EDDS
- EDSB
- EDTL
- LSZH
- LFSB
- LSZB
helligkeit: '0.5'
version: gafor
wind:
  frequenz: '1'
  hoch: '25'
  normal: '15'
wlan:
  passwort: '1234'
  ssid: FRITZ!Box 7590 TN
zeiten:
  an: '8'
  aus: '22'
  dauerbetrieb: 'false'
