farben:
  blitze: '#ffffff'
  helligkeit: '0.5'
  hoher_wind: '#ffff00'
  ifr: '#ff0000'
  ifr_bei_wind: '#7d0000'
  lifr: '#7d007d'
  lifr_bei_wind: '#4b004b'
  mvfr: '#0000ff'
  mvfr_bei_wind: '#00007d'
  vfr: '#00ff00'
  vfr_bei_wind: '#007d00'
wind:
  frequenz: '1'
  hoch: '25'
  normal: '15'
wlan:
  passwort: '12345678'
  ssid: FRITZ!BOX 1234
zeiten:
  an: '8'
  aus: '22'
